---
name: "tagged-release"

on:
  push:
    tags:
      - '*'

strategy:
  matrix:
    os: [ubuntu-latest]
  fail-fast: true

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
 
    steps:
      - name: Check tag
        run: |
          [[ echo "$GITHUB_REF_NAME" | grep -Pq '^[0-9]+\.[0-9]+.[0-9]+-arch[0-9]*$' ]] || exit 1
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: $GITHUB_REF_NAME
          
      - name: Pack archive
        run: |
          tar -cafv archlinux-linux-$GITHUB_REF_NAME.tar.gz --exclude=.git/ *
          sha512sum archlinux-linux-$GITHUB_REF_NAME.tar.gz > archlinux-linux-$GITHUB_REF_NAME.tar.gz.sha512
          
      - name: "Release"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            archlinux-linux-$GITHUB_REF_NAME.tar.gz
            archlinux-linux-$GITHUB_REF_NAME.tar.gz.sha512

            
